### ISSUE TITLE
连不到shadowsocks服务器啊

### ISSUE THREAD

**Issue by jun1st** [lettleprince/QLadder#1]
App开启后，direct 的站点能打开，需要翻墙的打不开，

同一个ss 服务，别的应用里就能打开，这个怎么调试呢？

**Comment by tonyh2021** [comment]
要自己搭建vpn，然后添加配置的。这个项目只相当于一个客户端，主要是用来展示 networkextension 的用法。

**Comment by jun1st** [comment]
有vpn，平时用surge，想来试下这个nekit

改了conf里的host地址，加密方法，

2018年1月30日 +0800 AM12:27 Tony Han <notifications@github.com>，写道：

**Comment by tonyh2021** [comment]
http://ibloodline.com/articles/2017/11/15/NetworkExtension-02.html

这个调试的文章看了么？看下走不走PacketTunnelProvider

**Comment by tonyh2021** [comment]
我先关掉了，如果有其他问题你再打开吧。
