### ISSUE TITLE
开发

### ISSUE THREAD

**Issue by sysbol** [lettleprince/QLadder#11]
你好，我openconnect搭建的服务起可以使用您的代码吧，我更改了 
private struct ProxyDictKey {
    static let name = ""
    static let host = ""
    static let port = ""
    static let passwd = ""
}
vpn 图标提示已经连接 但是上谷歌上不去，求教

**Comment by tonyh2021** [comment]
理论上是可以的，而且之前也都可以。但是最近几个月以来墙似乎升级了，导致 Shadowsocks 协议几乎无法正常使用。现在我使用的是 V2Ray 的 VMess 协议（当然由于协议更复杂，客户端很难自己实现，所以就用了第三方的）。
