### ISSUE TITLE
只有地址端口密码 没有协议吗？

### ISSUE THREAD

**Issue by azhm** [lettleprince/QLadder#3]
你好我编译完成 只看到有地址端口密码 没有协议吗？这是支持ss的是吗？

**Comment by tonyh2021** [comment]
是支持 SS 的，具体的代码可以看下 PacketTunnelProvider.swift，在这里进行用户名、密码、端口等相关的配置。
另外，调试细节可以看下这里：http://ibloodline.com/articles/2017/11/15/NetworkExtension-02.html

**Comment by azhm** [comment]
好的 我昨晚已经看到啦 感谢😁

**Comment by azhm** [comment]
你好这个支持ssr吗？ 我没看到配置混淆/协议的地方

**Comment by tonyh2021** [comment]
还是在 PacketTunnelProvider.swift 中，你说的加密协议是指这里吧？
```
        let algorithm:CryptoAlgorithm
        
        switch method{
        case "AES128CFB":algorithm = .AES128CFB
        case "AES192CFB":algorithm = .AES192CFB
        case "AES256CFB":algorithm = .AES256CFB
        case "CHACHA20":algorithm = .CHACHA20
        case "SALSA20":algorithm = .SALSA20
        case "RC4MD5":algorithm = .RC4MD5
        default:
            fatalError("Undefined algorithm!")
        }
```

我自己在用，所以就把这里的 `ss_method` 配置写死了。实际上是可以配置的。
```
conf["ss_method"] = "AES256CFB" as AnyObject? // 大写 没有横杠 看Extension中的枚举类设定 否则引发fatal error
```

**Comment by azhm** [comment]
这个ss的协议我昨晚看到了呢   我说的是ssr里面的混淆协议 Protocol / obfs

**Comment by azhm** [comment]
那请问一下怎么修改呢  我也想改成跟其他参数一下自己定义
我也是刚接触这个  感谢🙏

**Comment by tonyh2021** [comment]
我对 SS 和 SSR 并不是很熟悉。但是 `CHACHA20` 和 `RC4MD5` 应该就是 SSR 的协议吧?

https://github.com/shadowsocksr-backup/shadowsocks-rss/blob/master/ssr.md#%E6%B7%B7%E6%B7%86%E4%B8%8E%E5%8D%8F%E8%AE%AE%E9%85%8D%E7%BD%AE%E5%BB%BA%E8%AE%AE

**Comment by tonyh2021** [comment]
你想改成哪个协议？我看下能不能加上

另外，可以在 VpnManager.swift 中自己修改。"AES256CFB" 改成 "CHACHA20" "AES192CFB" 之类的就好了。
```
conf["ss_method"] = "AES256CFB" as AnyObject? // 大写 没有横杠 看Extension中的枚举类设定 否则引发fatal error

```

**Comment by azhm** [comment]
server IP :  127.0.0.1
server Port :  1024
password :  testtest
method : rc4-md5
protocol : origin 
obfs : plain
这是ssr的配置
我想添加上对ssr的支持  配置 protocol/obfs这两个参数 就是不知道在项目里面改。

**Comment by azhm** [comment]
@lettleprince ss的 method这个我已经看懂了会配置 就是想加入对ssr的支持

**Comment by tonyh2021** [comment]
@azhm  从 https://github.com/zhuhaow/NEKit/issues/90 以及 https://github.com/shadowsocks/shadowsocks-org/issues/64 来看，zhuhaow 暂时不会加入 SSR 的支持（zhuhaow 是本项目基础库 NEKit 的作者）。

**Comment by azhm** [comment]
好的呢 老哥你有telegram吗？
