### ISSUE TITLE
NEPacketTunnelProvider

### ISSUE THREAD

**Issue by MehmetSait** [lettleprince/QLadder#4]
hi, i download your project, but i can not start PacketTunnelProvider,
how can i start

**Comment by tonyh2021** [comment]
You should build the project in Xcode 9 with Swift4.

**Comment by MehmetSait** [comment]
hi TonHan, i build project and i run it than i connect vpn with fake
ip:port( like 127.0.0.0:9090), but i can not flow network packets. not
start PacketTunnelProvider class so tunnel not started and i can not flow
packets

I want to flow network packets specially DNS packet and tunnelling it, How
can i flow packet? what can i do it

Thank you for your help

2018-04-13 4:41 GMT+03:00 TonyHan <notifications@github.com>:

**Comment by chenguohao** [comment]
是的，我也遇到这个问题，传入正确的地址端口密码等参数，能开启VPN，但是无法上网

**Comment by tonyh2021** [comment]
> 是的，我也遇到这个问题，传入正确的地址端口密码等参数，能开启VPN，但是无法上网

之前我有遇到过这样的问题，基本是参数填写错误造成的，此时可以开启VPN，但是没法上网。所以我觉得你可以先检查下各项地址端口等参数。
如果还有问题，你可以将这些参数写死在代码中试试。
